import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="p-4 border-b flex gap-4 text-sm">
          <a href="/">▶︎診断</a>
          <a href="/results">▶︎保存された診断</a>
          <a href="/match/self">▶︎自分に似ている人</a>
          <a href="/match/compatibility">▶︎相性が良い人</a>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}